#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   ./scripts/generate_root_tf.sh enabled.txt
#
# enabled.txt format (single line):
#   enabled:alpha,beta

enabled_file="${1:-}"

if [[ -z "$enabled_file" || ! -f "$enabled_file" ]]; then
  echo "Usage: $0 <enabled.txt>" >&2
  exit 1
fi

out="root/generated.auto.tf"

echo "// Generated by CI. Do not edit." > "$out"
echo >> "$out"

line="$(<"$enabled_file")"
line="${line#enabled:}"

IFS=',' read -ra stacks <<< "$line"

for stack in "${stacks[@]}"; do
  [[ -z "$stack" ]] && continue
  cat >> "$out" <<HCL
module "$stack" {
  source              = "../stacks/$stack"
  resource_group_name = var.resource_group_name
}

HCL
done

echo "Wrote $out"
