#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   ./scripts/generate_root_tf.sh enabled.json
#
# enabled.json format:
# {
#   "enabled": ["alpha", "beta"]
# }

enabled_json="${1:-}"

if [[ -z "$enabled_json" || ! -f "$enabled_json" ]]; then
  echo "Usage: $0 <enabled.json>" >&2
  exit 1
fi

out="root/generated.auto.tf"

echo "// Generated by CI. Do not edit." > "$out"
echo >> "$out"

jq -r '.enabled[]' "$enabled_json" | while read -r stack; do
  cat >> "$out" <<HCL
module "$stack" {
  source              = "../stacks/$stack"
  resource_group_name = var.resource_group_name
}

HCL
done

echo "Wrote $out"
